apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Backup_Survey_PoC
  title: Backup Survey PoC
  description: Basic Survey template generation POC
  tags:
  - recommended
  - ansible
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
  - title: Provide information about the new component
    required:
    - seed_network_route
    properties:
      seed_network_route:
        title: Route information
        description: Route backup information
        type: string
        maxLength: 128
      inventory:
        title: Inventory
        type: string
        description: the inventory we point to
      organisation:
        title: Organisation
        type: string
        description: the Organisation we point to
  steps:
  - id: ansible portal
    name: Invokes the backend scaffolder plugin for Ansible portal exp
    action: ansible:rhaap:sync
    input:
      inventory: ${{ parameters.inventory }}
      aeConfig:
        seed_network_route: ${{ parameters.seed_network_route }}
      organisation: ${{ parameters.organisation }}
      appType: automationExperience
      appName: Backup_Survey_PoC
