apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Restore_Survey_PoC
  title: Restore Survey PoC
  description: POC template generation from Restore Survey
  tags:
  - recommended
  - ansible
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
  - title: Provide information about the new component
    required:
    - seed_cloud_restore_region
    - seed_cloud_restore_resource_group_name
    properties:
      seed_cloud_restore_region:
        title: Which restore region will your Arc servers reside?
        description: Specify the Restore region in which your arc servers reside
        type: string
        maxLength: 128
      seed_cloud_restore_resource_group_name:
        title: What is the name of your resource group?
        description: Specify the name of the resource group
        type: string
        maxLength: 128
      seed_cloud_restore_analytics_workspace_name:
        title: What is the name of your Log Analytics Workspace?
        description: Specify your Log Analyticss Workspace
        type: string
        maxLength: 128
      inventory:
        title: Inventory
        type: string
        description: the inventory we point to
      organisation:
        title: Organisation
        type: string
        description: the Organisation we point to
  steps:
  - id: ansible portal
    name: Invokes the backend scaffolder plugin for Ansible portal exp
    action: ansible:rhaap:sync
    input:
      inventory: ${{ parameters.inventory }}
      aeConfig:
        seed_cloud_restore_region: ${{ parameters.seed_cloud_restore_region }}
        seed_cloud_restore_resource_group_name: ${{ parameters.seed_cloud_restore_resource_group_name
          }}
        seed_cloud_restore_analytics_workspace_name: ${{ parameters.seed_cloud_restore_analytics_workspace_name
          }}
      organisation: ${{ parameters.organisation }}
      appType: automationExperience
      appName: Restore_Survey_PoC
